package paquetePrueba;


public class Tres {
		private static int metodo(){
		int valor = 0;
		try {
		valor = valor + 1; /* Valor vale 1 */
		valor = valor + Integer.parseInt("W"); /* Hay error, por lo que se va al catch y no se acaba de mostrar el try */
		valor = valor + 1 ;
		System.out.println ("Valor al final del try : " + valor);
		}
		catch (NumberFormatException e ) {
		valor = valor + Integer.parseInt("W"); /* Hay error, por lo que deber√≠a petar el programa */
		System.out.println("Valor al final del catch : " + valor);
		}
		finally {
		valor = valor + 1 ; /*  */
		System.out.println("Valor al final de finally : " + valor);
		}
		valor = valor + 1;
		System.out.println("Valor antes del return: " + valor);
		return valor;
		}
				public static void main (String [] args) {
				try {
				System.out.println (metodo ( ) ) ;
				}
				catch ( Exception e ) {
				System.err.println ("Excepcion en metodo ( ) ") ;
				}
				}
}
